export const ROUTES = {
  // Public
  HOME: '/',
  LOGIN: '/auth/login',
  REGISTER: '/auth/register',
  CONFIRM_EMAIL: '/auth/confirm-email',
  FORGOT_PASSWORD: '/auth/forgot-password',
  RESET_PASSWORD: '/auth/reset-password',
  RESEND_CONFIRMATION: '/auth/resend-confirmation',
  CANCEL_DELETION: '/auth/cancel-deletion',
  ONBOARDING: '/auth/onboarding',
  TERMS: '/terms',
  PRIVACY: '/privacy',
  CONTENT: '/content',
  CONTENT_DETAIL: (id: string) => `/content/${id}`,
  PRICING: '/#precos',
  SUPPORT: '/support',
  MAINTENANCE: '/maintenance',

  // Student
  DASHBOARD: '/dashboard',
  SCHEDULE: '/schedule',
  CREDITS: '/credits',
  PROGRESS: '/progress',
  SESSION: (id: string) => `/session/${id}`,
  ACCOUNT: '/account',
  ACCOUNT_BILLING: '/account/billing',
  HISTORY: '/history',

  // Admin
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_SCHEDULE: '/admin/schedule',
  ADMIN_STUDENTS: '/admin/students',
  ADMIN_SESSIONS: '/admin/sessions',
  ADMIN_CREDITS: '/admin/credits',
  ADMIN_REPORTS: '/admin/reports',
  ADMIN_CONTENT: '/admin/content',
  ADMIN_FEEDBACK: (sessionId: string) => `/admin/feedback/${sessionId}`,
} as const;

export const API = {
  V1: '/api/v1',
  AUTH: {
    REGISTER: '/api/v1/auth',
    LOGIN: '/api/v1/auth/login',
    LOGOUT: '/api/v1/auth/logout',
    ME: '/api/v1/auth/me',
    CONFIRM_EMAIL: '/api/v1/auth/confirm-email',
    RESEND_CONFIRMATION: '/api/v1/auth/resend-confirmation',
    FORGOT_PASSWORD: '/api/v1/auth/forgot-password',
    RESET_PASSWORD: '/api/v1/auth/reset-password',
    ONBOARDING: '/api/v1/auth/onboarding',
    DELETE_ACCOUNT: '/api/v1/auth/delete-account',
    EXPORT_DATA: '/api/v1/auth/export-data',
    COOKIE_CONSENT: '/api/v1/auth/cookie-consent',
    CANCEL_DELETION: '/api/v1/auth/cancel-deletion',
  },
  PROFILE: '/api/v1/profile',
  SESSIONS: '/api/v1/sessions',
  SESSION: (id: string) => `/api/v1/sessions/${id}`,
  SESSION_FEEDBACK: (id: string) => `/api/v1/sessions/${id}/feedback`,
  SESSION_SIGNAL: (id: string) => `/api/v1/sessions/${id}/signal`,
  SESSION_RESCHEDULE: (id: string) => `/api/v1/sessions/${id}/reschedule`,
  SESSION_APPROVE_RESCHEDULE: (id: string) => `/api/v1/sessions/${id}/approve-reschedule`,
  SESSION_CANCEL: (id: string) => `/api/v1/sessions/${id}/cancel`,
  SESSIONS_BULK_CANCEL: '/api/v1/sessions/bulk-cancel',
  CREDITS: '/api/v1/credits',
  CREDITS_MANUAL: '/api/v1/credits/manual',
  CHECKOUT: '/api/v1/checkout',
  PAYMENTS: '/api/v1/payments',
  SUBSCRIPTIONS: '/api/v1/subscriptions',
  SUBSCRIPTIONS_CANCEL: '/api/v1/subscriptions/cancel',
  SUBSCRIPTIONS_UPDATE: '/api/v1/subscriptions/update',
  FEEDBACK: '/api/v1/feedback',
  FEEDBACK_HISTORY: '/api/v1/feedback/history',
  FEEDBACK_PROGRESS: '/api/v1/feedback/progress',
  AVAILABILITY: '/api/v1/availability',
  AVAILABILITY_SLOT: (id: string) => `/api/v1/availability/${id}`,
  AVAILABILITY_BLOCK: (id: string) => `/api/v1/availability/${id}/block`,
  AVAILABILITY_UNBLOCK: (id: string) => `/api/v1/availability/${id}/unblock`,
  CONTENT: '/api/v1/content',
  CONTENT_DETAIL: (id: string) => `/api/v1/content/${id}`,
  CONTENT_NOTES: (id: string) => `/api/v1/content/${id}/notes`,
  ADMIN: {
    DASHBOARD: '/api/v1/admin/dashboard',
    USERS: '/api/v1/admin/users',
    USER: (id: string) => `/api/v1/admin/users/${id}`,
    STUDENTS: '/api/v1/admin/students',
    STUDENT: (id: string) => `/api/v1/admin/students/${id}`,
    SESSIONS: '/api/v1/admin/sessions',
    SESSION: (id: string) => `/api/v1/admin/sessions/${id}`,
    SESSION_FEEDBACK: (id: string) => `/api/v1/admin/sessions/${id}/feedback`,
    FEEDBACK_REVIEW: (id: string) => `/api/v1/admin/feedback/${id}/review`,
    CREDITS_NOTIFY_EXPIRING: '/api/v1/admin/credits/notify-expiring',
  },
  WEBHOOKS: {
    STRIPE: '/api/v1/webhooks/stripe',
  },
} as const;
