export const ROUTES = {
  // Public
  HOME: '/',
  LOGIN: '/auth/login',
  REGISTER: '/auth/register',
  CONFIRM_EMAIL: '/auth/confirm-email',
  FORGOT_PASSWORD: '/auth/forgot-password',
  RESET_PASSWORD: '/auth/reset-password',
  RESEND_CONFIRMATION: '/auth/resend-confirmation',
  MAGIC_LINK: '/auth/magic-link',
  CANCEL_DELETION: '/auth/cancel-deletion',
  ONBOARDING: '/auth/onboarding',
  TERMS: '/terms',
  PRIVACY: '/privacy',
  COOKIES: '/cookies',
  COOKIE_PREFERENCES: '/cookies/preferences',
  DPA: '/dpa',
  CONTENT: '/content',
  CONTENT_DETAIL: (id: string) => `/content/${id}`,
  PRICING: '/#precos',
  SUPPORT: '/support',
  SUPPORT_NEW: '/support/new',
  CONTACT: '/contact',
  MAINTENANCE: '/maintenance',

  // Student
  DASHBOARD: '/dashboard',
  SCHEDULE: '/schedule',
  CREDITS: '/credits',
  PROGRESS: '/progress',
  EXERCISES: '/exercises',
  ONBOARDING_EQUIPMENT: '/onboarding/equipment-check',
  SESSION: (id: string) => `/session/${id}`,
  SESSION_LOBBY: (id: string) => `/session/${id}/lobby`,
  SESSION_AUDIO_ONLY: (id: string) => `/session/${id}/audio-only`,
  SESSION_RECONNECTING: (id: string) => `/session/${id}/reconnecting`,
  SESSION_NOTES_RECOVERY: (id: string) => `/session/${id}/notes-recovery`,
  RESCHEDULE_OPTIONS: (bookingId: string) => `/schedule/${bookingId}/reschedule`,
  ACCOUNT: '/account',
  ACCOUNT_BILLING: '/account/billing',
  BILLING_SUBSCRIPTION: '/billing/subscription',
  BILLING_SUBSCRIPTION_CHANGE: '/billing/subscription/change-plan',
  HISTORY: '/history',
  LIBRARY: '/library',
  LIBRARY_DETAIL: (slug: string) => `/library/${slug}`,

  // Admin
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_SCHEDULE: '/admin/schedule',
  ADMIN_STUDENTS: '/admin/students',
  ADMIN_SESSIONS: '/admin/sessions',
  ADMIN_CREDITS: '/admin/credits',
  ADMIN_REPORTS: '/admin/reports',
  ADMIN_CONTENT: '/admin/content',
  ADMIN_EMAIL_TEMPLATES: '/admin/emails/templates',
  ADMIN_SUPPORT: '/admin/support',
  ADMIN_HEALTH: '/admin/health',
  ADMIN_ACCOUNT_SECURITY: '/admin/account/security',
  ADMIN_FEEDBACK: (sessionId: string) => `/admin/feedback/${sessionId}`,
  ADMIN_STUDENT_NOTES: (id: string) => `/admin/students/${id}/notes`,
  MFA_CHALLENGE: '/auth/mfa/challenge',
  MFA_SETUP: '/auth/mfa/setup',
} as const;

export const API = {
  V1: '/api/v1',
  AUTH: {
    REGISTER: '/api/v1/auth',
    LOGIN: '/api/v1/auth/login',
    LOGOUT: '/api/v1/auth/logout',
    ME: '/api/v1/auth/me',
    CONFIRM_EMAIL: '/api/v1/auth/confirm-email',
    RESEND_CONFIRMATION: '/api/v1/auth/resend-confirmation',
    FORGOT_PASSWORD: '/api/v1/auth/forgot-password',
    RESET_PASSWORD: '/api/v1/auth/reset-password',
    MAGIC_LINK_REQUEST: '/api/v1/auth/magic-link/request',
    ONBOARDING: '/api/v1/auth/onboarding',
    MFA_TOTP_INIT: '/api/v1/auth/mfa/totp/init',
    MFA_VERIFY: '/api/v1/auth/mfa/verify',
    DELETE_ACCOUNT: '/api/v1/auth/delete-account',
    EXPORT_DATA: '/api/v1/auth/export-data',
    COOKIE_CONSENT: '/api/v1/auth/cookie-consent',
    CANCEL_DELETION: '/api/v1/auth/cancel-deletion',
  },
  PROFILE: '/api/v1/profile',
  PROFILE_MARKETING_OPT_IN: '/api/v1/profile/marketing-opt-in',
  SESSIONS: '/api/v1/sessions',
  SESSION: (id: string) => `/api/v1/sessions/${id}`,
  SESSION_FEEDBACK: (id: string) => `/api/v1/sessions/${id}/feedback`,
  SESSION_SIGNAL: (id: string) => `/api/v1/sessions/${id}/signal`,
  SESSION_HEALTH_EVENTS: (id: string) => `/api/v1/sessions/${id}/health-events`,
  SESSION_INTERRUPT: (id: string) => `/api/v1/sessions/${id}/interrupt`,
  SESSION_RESCHEDULE: (id: string) => `/api/v1/sessions/${id}/reschedule`,
  SESSION_APPROVE_RESCHEDULE: (id: string) => `/api/v1/sessions/${id}/approve-reschedule`,
  SESSION_CANCEL: (id: string) => `/api/v1/sessions/${id}/cancel`,
  SESSION_NOTES_TOKEN: (id: string) => `/api/v1/sessions/${id}/notes/token`,
  SESSION_NOTES_SNAPSHOTS: (id: string) => `/api/v1/sessions/${id}/notes/snapshots`,
  SESSION_NOTES_RECOVER: (id: string) => `/api/v1/sessions/${id}/notes/recover`,
  SESSION_NOTES_EXPORT: (id: string) => `/api/v1/sessions/${id}/notes/export`,
  ICE_CONFIG: '/api/v1/ice-config',
  SESSIONS_BULK_CANCEL: '/api/v1/sessions/bulk-cancel',
  CREDITS: '/api/v1/credits',
  CREDITS_MANUAL: '/api/v1/credits/manual',
  CHECKOUT: '/api/v1/checkout',
  PAYMENTS: '/api/v1/payments',
  SUBSCRIPTIONS: '/api/v1/subscriptions',
  SUBSCRIPTIONS_CANCEL: '/api/v1/subscriptions/cancel',
  SUBSCRIPTIONS_UPDATE: '/api/v1/subscriptions/update',
  BILLING_SUBSCRIPTION_PREVIEW_CHANGE: '/api/v1/billing/subscription/preview-change',
  LEADS: '/api/v1/leads',
  FEEDBACK: '/api/v1/feedback',
  FEEDBACK_HISTORY: '/api/v1/feedback/history',
  FEEDBACK_PROGRESS: '/api/v1/feedback/progress',
  AVAILABILITY: '/api/v1/availability',
  AVAILABILITY_SLOT: (id: string) => `/api/v1/availability/${id}`,
  AVAILABILITY_BLOCK: (id: string) => `/api/v1/availability/${id}/block`,
  AVAILABILITY_UNBLOCK: (id: string) => `/api/v1/availability/${id}/unblock`,
  CONTENT: '/api/v1/content',
  CONTENT_DETAIL: (id: string) => `/api/v1/content/${id}`,
  CONTENT_NOTES: (id: string) => `/api/v1/content/${id}/notes`,
  REFERRALS: {
    ME: '/api/v1/referrals/me',
    INVITES: '/api/v1/referrals/invites',
    CREDITS: '/api/v1/referrals/credits',
    ACCEPT: '/api/v1/referrals/accept',
  },
  ADMIN: {
    AVAILABILITY: '/api/v1/admin/availability',
    DASHBOARD: '/api/v1/admin/dashboard',
    USERS: '/api/v1/admin/users',
    USER: (id: string) => `/api/v1/admin/users/${id}`,
    STUDENTS: '/api/v1/admin/students',
    STUDENT: (id: string) => `/api/v1/admin/students/${id}`,
    SESSIONS: '/api/v1/admin/sessions',
    SESSION: (id: string) => `/api/v1/admin/sessions/${id}`,
    SESSION_FEEDBACK: (id: string) => `/api/v1/admin/sessions/${id}/feedback`,
    FEEDBACK_REVIEW: (id: string) => `/api/v1/admin/feedback/${id}/review`,
    SUPPORT_TICKETS: '/api/v1/admin/support/tickets',
    SUPPORT_TICKET: (id: string) => `/api/v1/admin/support/tickets/${id}`,
    STUDENT_NOTES: (id: string) => `/api/v1/admin/students/${id}/notes`,
    CREDITS_NOTIFY_EXPIRING: '/api/v1/admin/credits/notify-expiring',
    BILLING_REFUNDS: '/api/v1/admin/billing/refunds',
    STRIPE_WEBHOOKS: '/api/v1/admin/webhooks/stripe',
  },
  WEBHOOKS: {
    STRIPE: '/api/v1/webhooks/stripe',
  },
  FX_PREVIEW: '/api/v1/fx/preview',
  BILLING_CHARGE_CURRENCY: '/api/v1/billing/charge-currency',
} as const;
