/** Barrel do modulo de exercicios do aluno. */

export { getExercises, getExerciseById } from './catalog';
export { contentLocaleFor, resolveLessonText } from './lesson-text';
export { distributeQuestion, moveItem, targetCorrectPosition } from './answer-distribution';
export { LESSON_1_PARROT } from './lesson-1-parrot';
export {
  EXERCISE_ITEM_KINDS,
  EXERCISE_ITEM_SCHEMAS_BY_KIND,
  MAX_FLEXIBLE_OPTIONS,
  MAX_MATCH_PAIRS,
  MIN_FLEXIBLE_OPTIONS,
  MIN_MATCH_PAIRS,
  PHASE_1_EXERCISE_ITEM_KINDS,
  VERB_CLOZE_MARKER,
  VERB_PERSONS,
  VERB_TENSES,
  exerciseEntryIdSchema,
  exerciseItemContentSchema,
  exerciseItemKindSchema,
  exerciseOptionTextSchema,
  exercisePromptSchema,
  matchClickAnswerKeySchema,
  matchClickPayloadSchema,
  matchEntrySchema,
  matchEntryTextSchema,
  multipleChoiceAnswerKeySchema,
  multipleChoicePayloadSchema,
  textChoiceAnswerKeySchema,
  textChoicePayloadSchema,
  verbClozeAnswerKeySchema,
  verbClozePayloadSchema,
  verbPersonSchema,
  verbTenseSchema,
  type ExerciseItemContent,
  type ExerciseItemKind,
  type MatchClickAnswerKey,
  type MatchClickPayload,
  type MatchEntry,
  type MultipleChoiceAnswerKey,
  type MultipleChoicePayload,
  type Phase1ExerciseItemKind,
  type TextChoiceAnswerKey,
  type TextChoicePayload,
  type VerbClozeAnswerKey,
  type VerbClozePayload,
  type VerbPerson,
  type VerbTense,
} from './exercise-item.schema';
export {
  OPTION_LETTERS,
  OPTIONS_PER_QUESTION,
  PLACEHOLDER_OPTIONS,
  type ExerciseKind,
  type GrammarPoint,
  type LessonContentLocale,
  type LessonExerciseSource,
  type LessonText,
  type OptionLetter,
  type SourceQuestion,
  type StaticExercise,
  type StaticExerciseOption,
  type StaticExerciseQuestion,
} from './types';
