-- AlterEnum: add BOOKING_RESCHEDULED to EmailType (module-9-integration ST008)
ALTER TABLE `email_logs`
  MODIFY COLUMN `type` ENUM(
    'CONFIRM_EMAIL',
    'BOOKING_CONFIRMED',
    'BOOKING_CANCELLED',
    'BOOKING_REMINDER_24H',
    'BOOKING_REMINDER_1H',
    'PASSWORD_RESET',
    'CREDIT_EXPIRY_WARNING',
    'PAYMENT_RECEIPT',
    'SUBSCRIPTION_CANCELLED',
    'BULK_CANCEL_NOTIFICATION',
    'PURCHASE_CONFIRMED',
    'SUBSCRIPTION_PAYMENT_FAILED',
    'SESSION_INTERRUPTED',
    'RECURRING_BOOKING_FAILED',
    'ACCOUNT_DELETION_REQUESTED',
    'DATA_EXPORT_READY',
    'FEEDBACK_AVAILABLE',
    'BOOKING_RESCHEDULED'
  ) NOT NULL;
